import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { MessageProvider } from "@/contexts/MessageContext";

const skModernist = localFont({
  src: "./fonts/Sk-Modernist-Regular.otf",
  variable: "--sk-modernist",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Daterrr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${skModernist.variable} ${skModernist.variable} antialiased`}>
        <AuthProvider>
          <MessageProvider>
            <Navbar />
            {children}
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
